### ISSUE TITLE
[Devlog]Roadmap v1.3.x

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-discordapp-module#19]
### Core Development
- [ ] ~~Implement webhooks to better connect to Discord.~~
- [ ] ~~Work Discord oauth into module settings.~~
- [x] Codebase reviewing.
- [x] Documentations
- [x] Review & Insight (#21)
- [x] Use of either DIscord domain (#37)

### Translations
- [ ] Translations (#12)

**Comment by Felli** [comment]
@ArchBlood I'm now assigning you to documentations
